### ISSUE TITLE
tried to install in Mac but getting error

### ISSUE THREAD

**Issue by yaskshelat** [conda-forge/arcsi-feedstock#4] opened 2018-02-20 01:46 UTC
Tried to install using condo forge and getting error in my MacBook (attached)
<img width="996" alt="screenshot at feb 19 20-45-02" src="https://user-images.githubusercontent.com/36253068/36403938-ea9d900a-15b5-11e8-8d8e-7328d8458c7c.png">
.
Can you please look into this?

**Comment by danclewley** [comment] 2018-02-20 19:21
Try installing using:

```
conda create -n arcsi_test -c conda-forge arcsi gsl
```

I've had problems with it pulling in `gsl` from defaults rather than conda-forge. Running:

```
conda update -c conda-forge --all
```
Normally fixes.

**Comment by yaskshelat** [comment] 2018-02-20 20:38
I run above commands in my windows machine now (windows was also giving me similar problems), but i still get attached error. I will try these commands on my mac tonight.
i need to work most of the times on windows so its more important for me to make this work on my windows machine.
<img width="425" alt="arcsi_error" src="https://user-images.githubusercontent.com/36253068/36447991-161c44ee-1654-11e8-81da-5d417b265bfc.png">

**Comment by petebunting** [comment] 2018-02-20 22:23
Try using python 3.5. I set up a couple of machines last Thursday with clean installations and that worked fine. 

Best wishes, 

Pete

**Comment by danclewley** [comment] 2018-02-21 07:29
@yaskshelat, can you confirm the commands I suggested work on macOS (they did for me) so we can close this issue about mac install problems.

**Comment by yaskshelat** [comment] 2018-02-21 13:50
hi yes, it works on my mac, it works when i added python=3.5 to my commands
Thanks for your suggestions...

**Comment by yaskshelat** [comment] 2018-02-21 14:13
**Windows installation:**

I still have problems with windows installation, even after adding python=3.5 at the end of the command suggested by dan
conda create -n arcsi_1 -c conda-forge arcsi gsl python=3.5
conda update -c conda-forge --all
I get the same error as showed below
<img width="425" alt="arcsi_error" src="https://user-images.githubusercontent.com/36253068/36484476-6c2fe6cc-16e7-11e8-9fe5-c937e33e901a.png">

**Comment by petebunting** [comment] 2018-02-21 16:16
It is difficult to comment, is the module actually installed OK? Can you send a list of the packages you have installed?

Run: conda list

Best wishes, 

Pete

**Comment by yaskshelat** [comment] 2018-02-21 18:53
(base) C:\Users\shelaty>conda list
# packages in environment at C:\Users\shelaty\AppData\Local\Continuum\anaconda2:

#
_ipyw_jlab_nb_ext_conf    0.1.0            py27h9111531_0
alabaster                 0.7.10           py27h2cab13d_0
anaconda                  custom           py27h689e5c3_0
anaconda-client           1.6.5            py27h9642776_0
anaconda-navigator        1.6.9            py27hd588ecf_0
anaconda-project          0.8.0            py27h56b7296_0
asn1crypto                0.22.0                   py27_0    conda-forge
astroid                   1.5.3            py27h658102e_0
astropy                   2.0.2            py27hbc6ace0_4
babel                     2.5.0            py27h50e9d34_0
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.5                      py27_0    conda-forge
backports.shutil_get_terminal_size 1.0.0            py27h1657125_2
backports_abc             0.5                      py27_0    conda-forge
basemap                   1.1.0                    py27_4    conda-forge
beautifulsoup4            4.6.0            py27hc287451_1
bitarray                  0.8.1            py27hc9ed29b_0
bkcharts                  0.2              py27h92b6de3_0
blaze                     0.11.3           py27h97e5449_0
bleach                    2.0.0            py27ha102ec9_0
bokeh                     0.12.10          py27h5ac3b79_0
boost                     1.66.0               py27_vc9_1  [vc9]  conda-forge
boost-cpp                 1.66.0                    vc9_1  [vc9]  conda-forge
boto                      2.48.0           py27h1ccb131_1
bottleneck                1.2.1            py27hde90680_0
bzip2                     1.0.6                     vc9_1  [vc9]  conda-forge
ca-certificates           2018.1.18                     0    conda-forge
cachecontrol              0.12.3           py27h15eca11_0
cdecimal                  2.3              py27h5b739fe_1
certifi                   2018.1.18                py27_0    conda-forge
cffi                      1.11.2                   py27_0    conda-forge
chardet                   3.0.4                    py27_0    conda-forge
click                     6.7              py27hb6defca_0
cloudpickle               0.4.0            py27h6dd55d0_0
clyent                    1.2.2            py27h4424948_1
colorama                  0.3.9                    py27_0    conda-forge
comtypes                  1.1.2            py27ha42e334_0
conda                     4.4.7                    py27_0
conda-build               3.0.27           py27hdc961ca_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py27h5217224_0
configparser              3.5.0            py27h2fa79a8_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py27h42efda5_0
cryptography              2.1.4                    py27_0    conda-forge
curl                      7.55.1                    vc9_0  [vc9]  conda-forge
cycler                    0.10.0                   py27_0    conda-forge
cython                    0.26.1           py27h45dccc8_0
cytoolz                   0.8.2            py27h44eb5fa_0
dask                      0.15.3           py27h206fe23_0
dask-core                 0.15.3           py27h436ea3d_0
datashape                 0.5.4            py27h3d6e61b_0
decorator                 4.1.2            py27h383e199_0
distlib                   0.2.5            py27hbc39c7c_0
distributed               1.19.1           py27heeda6fb_0
docutils                  0.14             py27h8652d09_0
entrypoints               0.2.3            py27h0271f2b_2
enum34                    1.1.6                    py27_1    conda-forge
et_xmlfile                1.0.1            py27h1de5d23_0
expat                     2.2.5                     vc9_0  [vc9]  conda-forge
fastcache                 1.0.2            py27hf477a8b_0
filelock                  2.0.12           py27h7a543d8_0
flask                     0.12.2           py27h30d9212_0
flask-cors                3.0.3            py27h4926b05_0
freetype                  2.8.1                     vc9_0  [vc9]  conda-forge
freexl                    1.0.4                     vc9_0  [vc9]  conda-forge
funcsigs                  1.0.2            py27h8885ae1_0
functools32               3.2.3.2                  py27_2    conda-forge
futures                   3.1.1            py27h71313b4_0
gdal                      2.2.3                py27_vc9_0  [vc9]  conda-forge
geos                      3.6.2                     vc9_1  [vc9]  conda-forge
geotiff                   1.4.2                     vc9_1  [vc9]  conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py27h1842022_0
glob2                     0.5              py27h5738e64_1
greenlet                  0.4.12           py27h32400d3_0
grin                      1.2.1            py27hb905a94_1
h5py                      2.7.0            py27hae8a57c_1
hdf4                      4.2.13                    vc9_0  [vc9]  conda-forge
hdf5                      1.10.1                    vc9_1  [vc9]  conda-forge
heapdict                  1.0.0            py27h5528e5e_0
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                      vc9_0  [vc9]  conda-forge
idna                      2.6                      py27_1    conda-forge
imageio                   2.2.0            py27h283db88_0
imagesize                 0.7.1            py27h1482bd8_0
intel-openmp              2018.0.0             hd92c6cd_8
ipaddress                 1.0.18                   py27_0    conda-forge
ipykernel                 4.6.1            py27h30cef79_0
ipython                   5.4.1            py27hbf971b4_1
ipython_genutils          0.2.0            py27hbe997df_0
ipywidgets                7.0.0            py27he0f823d_0
isort                     4.2.15           py27hdc949c3_0
itsdangerous              0.24             py27hcf63135_1
jdcal                     1.3              py27h8c72977_0
jedi                      0.10.2           py27h4f12af3_0
jinja2                    2.9.6            py27hb525989_1
jpeg                      9b                        vc9_2  [vc9]  conda-forge
jsonschema                2.6.0            py27haaf3834_0
jupyter                   1.0.0            py27h9d2e098_2
jupyter_client            5.1.0            py27hced1786_0
jupyter_console           5.2.0            py27h6ed736b_1
jupyter_core              4.3.0            py27h7bec3d2_0
jupyterlab                0.27.0           py27h573f66c_2
jupyterlab_launcher       0.4.0            py27ha72e593_0
kealib                    1.4.7                     vc9_4  [vc9]  conda-forge
krb5                      1.14.2                    vc9_0  [vc9]  conda-forge
lazy-object-proxy         1.3.1            py27ha5c8080_0
libboost                  1.65.1               h95ae18b_4
libgdal                   2.2.3                     vc9_3  [vc9]  conda-forge
libiconv                  1.15                      vc9_0  [vc9]  conda-forge
libkml                    1.3.0                h1826281_3
libnetcdf                 4.4.1.1                  vc9_10  [vc9]  conda-forge
libpng                    1.6.34                    vc9_0  [vc9]  conda-forge
libpq                     9.6.3                     vc9_0  [vc9]  conda-forge
libspatialite             4.3.0a                   vc9_19  [vc9]  conda-forge
libssh2                   1.8.0                     vc9_2  [vc9]  conda-forge
libtiff                   4.0.9                     vc9_0  [vc9]  conda-forge
libxml2                   2.9.5                     vc9_2  [vc9]  conda-forge
libxslt                   1.1.32                    vc9_0  [vc9]  conda-forge
llvmlite                  0.20.0                   py27_0
locket                    0.2.0            py27h1ca288a_1
lockfile                  0.12.2                   py27_0    conda-forge
lxml                      4.1.0            py27h5006083_0
lzo                       2.10                      vc9_0  [vc9]  conda-forge
markupsafe                1.0              py27h9d4480d_1
matplotlib                2.1.2                    py27_0    conda-forge
mccabe                    0.6.1            py27hde0bf6e_1
menuinst                  1.4.10           py27hf5e3df7_0
mistune                   0.7.4            py27h0f41fca_0
mkl                       2018.0.1             h2108138_4
mkl-service               1.1.2            py27h3c6b6b0_4
mpmath                    0.19             py27h2868657_2
msgpack-python            0.5.1                    py27_0    conda-forge
multipledispatch          0.4.9            py27h8ebb51e_0
navigator-updater         0.1.0            py27h5e42984_0
nbconvert                 5.3.1            py27h7a573cf_0
nbformat                  4.4.0            py27hf49b375_0
networkx                  2.0              py27h42253ca_0
nltk                      3.2.4            py27hfcc2c94_0
nose                      1.3.7                    py27_2    conda-forge
notebook                  5.0.0            py27h73e74a6_2
numba                     0.35.0             np113py27_10
numexpr                   2.6.4                    py27_1    conda-forge
numpy                     1.13.3           py27hfef472a_2
numpydoc                  0.7.0            py27hf7b062b_0
odo                       0.5.1            py27h64810b2_0
olefile                   0.44             py27h42675a9_0
openjpeg                  2.3.0                     vc9_2  [vc9]  conda-forge
openpyxl                  2.4.8            py27hbb31d20_1
openssl                   1.0.2n                    vc9_0  [vc9]  conda-forge
packaging                 16.8                     py27_0    conda-forge
pandas                    0.20.3           py27he04484b_2
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py27h76461d3_1
partd                     0.3.8            py27h1e0692f_0
path.py                   10.3.1           py27hc415bcf_0
pathlib2                  2.3.0            py27h0ae272f_0
patsy                     0.4.1            py27h5f67e4e_0
pep8                      1.7.0            py27h348567b_0
pickleshare               0.7.4            py27hb5f6335_0
pillow                    4.2.1            py27hbae4915_0
pip                       9.0.1                    py27_1    conda-forge
pkginfo                   1.4.1            py27h6ce81e3_1
ply                       3.10             py27h5fb8a85_0
progress                  1.3                      py27_0    conda-forge
proj4                     4.9.3                     vc9_5  [vc9]  conda-forge
prompt_toolkit            1.0.15           py27h3a8ec6a_0
psutil                    5.4.0            py27h12f019a_0
py                        1.4.34           py27h50228bf_1
pycodestyle               2.3.1            py27h24cd5d9_0
pycosat                   0.6.3            py27hcd410c5_0
pycparser                 2.18                     py27_0    conda-forge
pycrypto                  2.6.1            py27h0cf9ff2_1
pycurl                    7.43.0           py27h4a6fa90_3
pyflakes                  1.6.0            py27h34e7826_0
pygments                  2.2.0            py27ha50f84f_0
pyhdf                     0.9.0                    py27_2    conda-forge
pylint                    1.7.4            py27h1f1ce2c_0
pyodbc                    4.0.17           py27h79aec81_0
pyopenssl                 17.2.0                   py27_0    conda-forge
pyparsing                 2.2.0                    py27_0    conda-forge
pyproj                    1.9.5.1                  py27_0    conda-forge
pyqt                      5.6.0                    py27_4    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py27_1    conda-forge
pytables                  3.4.2            py27h583b7c0_2
pytest                    3.2.1            py27h7cb0baa_1
python                    2.7.14                        4    conda-forge
python-dateutil           2.6.1                    py27_0    conda-forge
python-snappy             0.5.1                    py27_2    conda-forge
pytz                      2018.3                     py_0    conda-forge
pywavelets                0.5.2            py27h0dc3f48_0
pywin32                   221              py27h5035e5b_0
pyyaml                    3.12             py27ha287073_1
pyzmq                     16.0.2           py27h7554bf6_2
qt                        5.6.2                     vc9_1  [vc9]  conda-forge
qtawesome                 0.4.4            py27h766b13d_0
qtconsole                 4.3.1            py27h77d40ac_0
qtpy                      1.3.1            py27h1ff2b4b_0
requests                  2.18.4                   py27_1    conda-forge
rope                      0.10.5           py27h927ae9b_0
ruamel_yaml               0.11.14          py27hce2a281_2
scandir                   1.6              py27h518bda0_0
scikit-image              0.13.0           py27h27e3c36_1
scikit-learn              0.19.1           py27he00e316_0
scipy                     1.0.0            py27h7cd1477_0
seaborn                   0.8.0            py27h5729117_0
setuptools                38.5.1                   py27_0    conda-forge
simplegeneric             0.8.1            py27h2c3a90d_0
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.18                     py27_1    conda-forge
six                       1.11.0                   py27_1    conda-forge
snappy                    1.1.7                     vc9_1  [vc9]  conda-forge
snowballstemmer           1.2.1            py27h28d3bf7_0
sortedcollections         0.5.3            py27h21b938c_0
sortedcontainers          1.5.7            py27hb302113_0
sphinx                    1.6.3            py27h858dd0f_0
sphinxcontrib             1.0              py27h0e2fb95_1
sphinxcontrib-websupport  1.0.1            py27h0d0f901_1
spyder                    3.2.4            py27hbf7a773_0
sqlalchemy                1.1.13           py27had82547_0
sqlite                    3.20.1                    vc9_2  [vc9]  conda-forge
ssl_match_hostname        3.5.0.1                  py27_1    conda-forge
statsmodels               0.8.0            py27hc77c1fc_0
subprocess32              3.2.7                    py27_0    conda-forge
sympy                     1.1.1            py27hde44fae_0
tblib                     1.3.2            py27h8ae915c_0
testpath                  0.3.1            py27h1cd488d_0
tk                        8.6.7                     vc9_0  [vc9]  conda-forge
toolz                     0.8.2            py27h1873a47_0
tornado                   4.5.3                    py27_0    conda-forge
traitlets                 4.3.2            py27h1b1b3a5_0
typing                    3.6.2            py27h9197bb0_0
unicodecsv                0.14.1           py27h0bf7bb0_0
urllib3                   1.22                     py27_0    conda-forge
vc                        9                             0    conda-forge
vs2008_runtime            9.0.30729.6161                0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7            py27hb1a0d82_0
webencodings              0.5                      py27_0    conda-forge
werkzeug                  0.12.2           py27h822ccf9_0
wheel                     0.30.0                   py27_2    conda-forge
widgetsnbextension        3.0.2            py27h599da02_1
win_inet_pton             1.0.1                    py27_1    conda-forge
win_unicode_console       0.5              py27hc037021_0
wincertstore              0.2                      py27_0    conda-forge
wrapt                     1.10.11          py27hcd2b27d_0
xerces-c                  3.2.0                     vc9_0  [vc9]  conda-forge
xlrd                      1.1.0            py27h2b87a7f_1
xlsxwriter                1.0.2            py27h5ed79b1_0
xlwings                   0.11.4           py27h0373cff_0
xlwt                      1.3.0            py27h2271735_0
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                     vc9_0  [vc9]  conda-forge
zict                      0.1.3            py27h0171463_0
zlib                      1.2.11                    vc9_0  [vc9]  conda-forge

(base) C:\Users\shelaty>conda activate arcsi_1

(arcsi_1) C:\Users\shelaty>arcsi.py -h
Traceback (most recent call last):
  File "C:\Users\shelaty\AppData\Local\Continuum\anaconda2\envs\arcsi_1\Scripts\
arcsi.py", line 52, in <module>
    import arcsilib
ImportError: No module named arcsilib

(arcsi_1) C:\Users\shelaty>

**Comment by yaskshelat** [comment] 2018-02-21 18:55
I have created environment arcsi_1 inside anaconda which has following packages, above packages are list of ALL packages inside anaconda, i believe it is more relevant to know about packages inside arcsi_1 environment.

(arcsi_1) C:\Users\shelaty>conda list
# packages in environment at C:\Users\shelaty\AppData\Local\Continuum\anaconda2\
envs\arcsi_1:
#
arcsi                     2.2.24              py35_vc14_1  [vc14]  conda-forge
backports                 1.0                      py35_1    conda-forge
backports.functools_lru_cache 1.5                      py35_0    conda-forge
boost                     1.66.0              py35_vc14_1  [vc14]  conda-forge
boost-cpp                 1.66.0                   vc14_1  [vc14]  conda-forge
ca-certificates           2018.1.18                     0    conda-forge
certifi                   2018.1.18                py35_0    conda-forge
cgal                      4.11                py35_vc14_2  [vc14]  conda-forge
curl                      7.55.1                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                   py35_0    conda-forge
expat                     2.2.5                    vc14_0  [vc14]  conda-forge
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
freexl                    1.0.2                    vc14_2  [vc14]  conda-forge
gdal                      2.2.3                    py35_0    conda-forge
geos                      3.6.2                    vc14_1  [vc14]  conda-forge
geotiff                   1.4.2                    vc14_1  [vc14]  conda-forge
gsl                       2.2.1                    vc14_4  [vc14]  conda-forge
h5py                      2.7.1                    py35_2    conda-forge
hdf4                      4.2.13                   vc14_0  [vc14]  conda-forge
hdf5                      1.10.1                   vc14_1  [vc14]  conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
intel-openmp              2018.0.0             hd92c6cd_8
jpeg                      9b                       vc14_2  [vc14]  conda-forge
kealib                    1.4.7                    vc14_4  [vc14]  conda-forge
krb5                      1.14.2                   vc14_0  [vc14]  conda-forge
libgdal                   2.2.3                    vc14_3  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libnetcdf                 4.4.1.1                 vc14_10  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libpq                     9.6.3                    vc14_0  [vc14]  conda-forge
libspatialite             4.3.0a                  vc14_19  [vc14]  conda-forge
libssh2                   1.8.0                    vc14_2  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
matplotlib                2.1.2                    py35_0    conda-forge
mkl                       2018.0.1             h2108138_4
mpfr                      3.1.5                    vc14_0  [vc14]  conda-forge
mpir                      3.0.0                    vc14_0  [vc14]  conda-forge
msys2-conda-epoch         20160418                      1
muparser                  2.2.5                    vc14_2  [vc14]  conda-forge
numpy                     1.14.0           py35h4a99626_1
openjpeg                  2.3.0                    vc14_2  [vc14]  conda-forge
openssl                   1.0.2n                   vc14_0  [vc14]  conda-forge
pip                       9.0.1                    py35_1    conda-forge
proj4                     4.9.3                    vc14_5  [vc14]  conda-forge
py6s                      1.7.0                    py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_4    conda-forge
pysolar                   0.6                      py35_0    conda-forge
python                    3.5.5                         0    conda-forge
python-dateutil           2.6.1                    py35_0    conda-forge
pytz                      2018.3                     py_0    conda-forge
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
rios                      1.4.4                    py35_0    conda-forge
rsgislib                  3.4.9               py35_vc14_1  [vc14]  conda-forge
scikit-learn              0.19.1           py35h2037775_0
scipy                     1.0.0            py35h75710e8_0
setuptools                38.5.1                   py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.11.0                   py35_1    conda-forge
sixs                      1.1                           0    conda-forge
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
tornado                   4.5.3                    py35_0    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.30.0                   py35_2    conda-forge
wincertstore              0.2                      py35_0    conda-forge
xerces-c                  3.2.0                    vc14_0  [vc14]  conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

(arcsi_1) C:\Users\shelaty>

**Comment by gillins** [comment] 2018-02-21 19:54
Can you try running `arcsi.py.bat` and see if that works?

**Comment by yaskshelat** [comment] 2018-02-22 14:33
**Windows**
I tried arcsi.py.bat and it can recognize arcsi.py.
however I tried to run it with following commands on windows
arcsi.py.bat -s sen2 -f KEA --fullimgouts -p SREF --aeropro Maritime --atmospro SubarcticSummer --aot 0.25 --surfacealtitude 0.4 -o C:\WORK_FILES\scratch\S2A_MSIL1C_20171028T200541_N0206_R128_T08UPF_20171028T214830.SAFE -i C:\WORK_FILES\scratch\S2A_MSIL1C_20171028T200541_N0206_R128_T08UPF_20171028T214830.SAFE\MTD_MSIL1C.xml -t C:\WORK_FILES\scratch\temp
I have already followed this thread to change line 711 of arcsisensorsentinel2.py.
https://groups.google.com/forum/#!topic/rsgislib-support/QsEn4ziB5gI

it still gives me error as attached in a snapshot below
<img width="422" alt="arcsi_error_1" src="https://user-images.githubusercontent.com/36253068/36543935-2dea0330-17b3-11e8-9f95-d7e219c38426.png">

**Comment by petebunting** [comment] 2018-02-22 14:50
Can you run with --debug and hopefully it will print more information on where the error is occurring.

**Comment by yaskshelat** [comment] 2018-02-22 15:02
Here is it with --debug (below snapshot), in a snapshot from my previous message, i see that "image base name" comes out with lat long, is this usual or something is wrong there?
<img width="424" alt="arcsi_error_2" src="https://user-images.githubusercontent.com/36253068/36545570-32a2d01a-17b7-11e8-9502-cf27113e22af.png">

**Comment by yaskshelat** [comment] 2018-02-22 15:12
it produces one of the following resampled bands with following name
SEN2_20171028_lat55lon13255_T08UPG_ORB128_utm8n_B05_10m.kea
To me "output Base name" doesnt sound right
Yask

**Comment by petebunting** [comment] 2018-02-22 15:37
The output base name looks OK. ARCSI automatically puts the centre lat/long into the file name for all images.

It look to be like this is error coming out of GDAL somewhere and I would bet it is a difference between Windows vs Linux/MacOS/UNIX. Unfortunately, I do not have a windows computer in my lab so I am not able to test this myself. We run ARCSI/RSGISLib extensively on Linux/MacOS but very rarely on Windows so I am not surprised these type of errors crop up.

**Comment by gillins** [comment] 2018-02-22 20:19
`arcsi.py` and `arcsi.py.bat` *should* do the same thing. I'm traveling at the moment but will have a proper look when i get back. 
Just checking - do you have a `arcsi.py` in your current directory by any chance?

**Comment by danclewley** [comment] 2018-02-27 07:13
I'm going to close this as it looks like ARCSI installs OK on macOS and Windows. The problem is with some of the functions in RSGISLib not working as expected on Windows.

**Closed as completed by danclewley** 2018-02-27 07:13 UTC
